### ISSUE TITLE
Create Epic for Business Prospecting.

### ISSUE THREAD

**Issue by fealgu1** [fealgu1/Daily_Proj#78]
This project will create a list of potential retail customers for Wolt. The goal is to identify the most fit customer so that sales can target

**Comment by fealgu1** [comment]
- [x] As SDM, I want to find all our current partners, so we can research their product lines and charatericstics. 
- [x] As SDM, I want to research clients  that may benifit from our service, so we can add them as partners.
- [x] As SDM, I want to create list of businessess organized by business attributes so I can build a report of top prospects.
- [ ] As SDM, I want to create business personas for each potential business so I can learn more about each prospect.
